# Generated by Django 3.1.5 on 2021-01-16 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(db_column='Industry', max_length=100, unique=True)),
                ('avg_margin', models.DecimalField(blank=True, db_column='avgMargin', decimal_places=14, max_digits=33, null=True)),
                ('avg_leverage', models.DecimalField(blank=True, db_column='avgLeverage', decimal_places=14, max_digits=33, null=True)),
                ('avg_dividend_yield', models.FloatField(blank=True, db_column='avgDividendYield', null=True)),
                ('avg_assets_turnover', models.DecimalField(blank=True, db_column='avgAssetsTurnover', decimal_places=10, max_digits=51, null=True)),
            ],
            options={
                'db_table': 'Industries',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(db_column='Sector', max_length=100, unique=True)),
                ('avg_margin_sector', models.DecimalField(blank=True, db_column='avgMarginSector', decimal_places=14, max_digits=33, null=True)),
                ('avg_leverage_sector', models.DecimalField(blank=True, db_column='avgLeverageSector', decimal_places=14, max_digits=33, null=True)),
                ('avg_dividend_yield_sector', models.FloatField(blank=True, db_column='avgDividendYieldSector', null=True)),
                ('avg_assets_turnover_sector', models.DecimalField(blank=True, db_column='avgAssetsTurnoverSector', decimal_places=10, max_digits=51, null=True)),
            ],
            options={
                'db_table': 'sectors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tickers',
            fields=[
                ('ticker', models.CharField(db_column='Ticker', max_length=10, primary_key=True, serialize=False)),
                ('shortname', models.CharField(blank=True, db_column='ShortName', max_length=100, null=True)),
                ('beta', models.FloatField(blank=True, db_column='Beta', null=True)),
                ('forwardpe', models.FloatField(blank=True, db_column='ForwardPE', null=True)),
                ('dividendyield', models.FloatField(blank=True, db_column='DividendYield', null=True)),
                ('nextearningsdate', models.DateField(blank=True, db_column='NextEarningsDate', null=True)),
                ('industry', models.ForeignKey(db_column='Industry', on_delete=django.db.models.deletion.CASCADE, to='stocks.industries', to_field='industry')),
                ('sector', models.ForeignKey(db_column='Sector', on_delete=django.db.models.deletion.CASCADE, to='stocks.sectors', to_field='sector')),
            ],
            options={
                'db_table': 'tickers',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='industries',
            name='sector',
            field=models.ForeignKey(db_column='Sector', on_delete=django.db.models.deletion.CASCADE, to='stocks.sectors', to_field='sector'),
        ),
        migrations.CreateModel(
            name='Rawdatayearly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enddate', models.DateField(db_column='EndDate')),
                ('cfoperations', models.DecimalField(db_column='cfOperations', decimal_places=2, max_digits=15)),
                ('dividendspaid', models.DecimalField(db_column='DividendsPaid', decimal_places=2, max_digits=15)),
                ('stockissuance', models.DecimalField(db_column='StockIssuance', decimal_places=2, max_digits=15)),
                ('totalassets', models.DecimalField(db_column='TotalAssets', decimal_places=2, max_digits=15)),
                ('totallongtermdebt', models.DecimalField(db_column='TotalLongTermDebt', decimal_places=2, max_digits=15)),
                ('totalcurrentassets', models.DecimalField(db_column='TotalCurrentAssets', decimal_places=2, max_digits=15)),
                ('totalcurrentliabilities', models.DecimalField(db_column='TotalCurrentLiabilities', decimal_places=2, max_digits=15)),
                ('totalrevenue', models.DecimalField(db_column='TotalRevenue', decimal_places=2, max_digits=15)),
                ('netincomecontinuingops', models.DecimalField(db_column='NetIncomeContinuingOps', decimal_places=2, max_digits=15)),
                ('publicationdate', models.DateField(blank=True, db_column='PublicationDate', null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.tickers')),
            ],
            options={
                'db_table': 'rawdatayearly',
                'managed': True,
                'unique_together': {('ticker', 'enddate')},
            },
        ),
        migrations.CreateModel(
            name='Rawdataquarterly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enddate', models.DateField(db_column='EndDate')),
                ('cfoperations', models.DecimalField(db_column='cfOperations', decimal_places=2, max_digits=15)),
                ('dividendspaid', models.DecimalField(db_column='DividendsPaid', decimal_places=2, max_digits=15)),
                ('stockissuance', models.DecimalField(db_column='StockIssuance', decimal_places=2, max_digits=15)),
                ('totalassets', models.DecimalField(db_column='TotalAssets', decimal_places=2, max_digits=15)),
                ('totallongtermdebt', models.DecimalField(db_column='TotalLongTermDebt', decimal_places=2, max_digits=15)),
                ('totalcurrentassets', models.DecimalField(db_column='TotalCurrentAssets', decimal_places=2, max_digits=15)),
                ('totalcurrentliabilities', models.DecimalField(db_column='TotalCurrentLiabilities', decimal_places=2, max_digits=15)),
                ('totalrevenue', models.DecimalField(db_column='TotalRevenue', decimal_places=2, max_digits=15)),
                ('netincomecontinuingops', models.DecimalField(db_column='NetIncomeContinuingOps', decimal_places=2, max_digits=15)),
                ('earningssurprise', models.FloatField(blank=True, db_column='EarningsSurprise', null=True)),
                ('publicationdate', models.DateField(blank=True, db_column='PublicationDate', null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.tickers')),
            ],
            options={
                'db_table': 'rawdataquarterly',
                'managed': True,
                'unique_together': {('ticker', 'enddate')},
            },
        ),
        migrations.CreateModel(
            name='Bosscompensations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='Date')),
                ('paymentsum', models.DecimalField(blank=True, db_column='PaymentSum', decimal_places=0, max_digits=10, null=True)),
                ('marketcap', models.DecimalField(blank=True, db_column='MarketCap', decimal_places=0, max_digits=14, null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.tickers')),
            ],
            options={
                'db_table': 'bosscompensations',
                'managed': True,
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
