# Generated by Django 3.1.5 on 2021-01-17 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickersAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(blank=True, db_column='ShortName', max_length=100, null=True)),
                ('beta', models.FloatField(blank=True, db_column='Beta', null=True)),
                ('forwardpe', models.FloatField(blank=True, db_column='ForwardPE', null=True)),
                ('dividendyield', models.FloatField(blank=True, db_column='DividendYield', null=True)),
                ('sector', models.CharField(blank=True, db_column='Sector', max_length=100, null=True)),
                ('nextearningsdate', models.DateField(blank=True, db_column='NextEarningsDate', null=True)),
                ('cfpositive', models.BooleanField(blank=True, db_column='cfPositive', null=True)),
                ('nostockissuance', models.BooleanField(blank=True, db_column='NoStockIssuance', null=True)),
                ('margin', models.DecimalField(blank=True, db_column='Margin', decimal_places=10, max_digits=29, null=True)),
                ('leverage', models.DecimalField(blank=True, db_column='Leverage', decimal_places=10, max_digits=29, null=True)),
                ('liquidity', models.DecimalField(blank=True, db_column='Liquidity', decimal_places=10, max_digits=29, null=True)),
                ('assetsturnover', models.DecimalField(blank=True, db_column='AssetsTurnover', decimal_places=6, max_digits=47, null=True)),
                ('industry', models.ForeignKey(db_column='Industry', on_delete=django.db.models.deletion.CASCADE, to='stocks.industries', to_field='industry')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.tickers')),
            ],
            options={
                'db_table': 'tickersaggregate',
                'managed': True,
            },
        ),
    ]
