# Generated by Django 3.1.5 on 2021-02-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20210118_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickers',
            name='assetsturnover',
            field=models.DecimalField(blank=True, db_column='AssetsTurnover', decimal_places=6, max_digits=47, null=True),
        ),
        migrations.AddField(
            model_name='tickers',
            name='cfpositive',
            field=models.BooleanField(blank=True, db_column='cfPositive', null=True),
        ),
        migrations.AddField(
            model_name='tickers',
            name='leverage',
            field=models.DecimalField(blank=True, db_column='Leverage', decimal_places=10, max_digits=29, null=True),
        ),
        migrations.AddField(
            model_name='tickers',
            name='liquidity',
            field=models.DecimalField(blank=True, db_column='Liquidity', decimal_places=10, max_digits=29, null=True),
        ),
        migrations.AddField(
            model_name='tickers',
            name='margin',
            field=models.DecimalField(blank=True, db_column='Margin', decimal_places=10, max_digits=29, null=True),
        ),
        migrations.AddField(
            model_name='tickers',
            name='nostockissuance',
            field=models.BooleanField(blank=True, db_column='NoStockIssuance', null=True),
        ),
        migrations.AlterField(
            model_name='tickers',
            name='sector',
            field=models.CharField(blank=True, db_column='Sector', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='TickersAggregate',
        ),
    ]
