# Generated by Django 3.1.5 on 2021-02-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20210204_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickers',
            name='dividendyield',
            field=models.FloatField(db_column='DividendYield', default=0),
        ),
        migrations.AlterField(
            model_name='tickers',
            name='forwardpe',
            field=models.FloatField(db_column='ForwardPE', default=0),
        ),
        migrations.AlterField(
            model_name='tickers',
            name='leverage',
            field=models.DecimalField(db_column='Leverage', decimal_places=10, default=0, max_digits=29),
        ),
        migrations.AlterField(
            model_name='tickers',
            name='margin',
            field=models.DecimalField(db_column='Margin', decimal_places=10, default=0, max_digits=29),
        ),
    ]
